export const projects = [
  {
    id: 1,
    name: 'Majors Golf Pool',
    image: '/tiger.png',
    description: 'A live scoring spreadsheet for a custom golf pool that I run for my friends.',
    link: 'https://docs.google.com/spreadsheets/d/10Q5XW0jEqfZiaBxc6iqkm9za4CxhTlpeuhS2RgxieYI/edit?usp=sharing',
    tags: ['Technical', 'In-progress'],
  },
  {
    id: 2,
    name: 'Golf Pool Entry Form',
    image: '/poolform.png',
    description: 'A dynamic web form that manages entries into my golf pool.',
    link: 'https://github.com/toddbalwinski/GolfPoolEntryForm',
    tags: ['Technical', 'In-progress'],
  },
  {
    id: 3,
    name: 'Twitter to Bluesky Bot',
    image: '/xtobsky.png',
    description: 'A Python-based bot to automatically reposts a users X posts to Bluesky in real time.',
    link: 'https://github.com/toddbalwinski/TwitterToBlueskyBot',
    tags: ['Technical'],
  },
  {
    id: 4,
    name: 'Vehicle Cataloging and Lending App',
    image: '/porsche.png',
    description: 'A cataloging and lending app for vehicles. This project was developed as part of a CS 3240 team project at UVA.',
    link: 'https://github.com/toddbalwinski/VehicleCatalogingAndLendingApp',
    tags: ['Technical'],
  },
  {
    id: 5,
    name: 'Course Review App',
    image: '/coursereview.png',
    description: 'A course review web app with CRUD functionality. This project was developed as part of CS 3140 team project at UVA.',
    link: 'https://github.com/toddbalwinski/CourseReviewApp',
    tags: ['Technical'],
  },
  {
    id: 6,
    name: 'Developing a Vulnerable System Ethics Case',
    image: '/ethics.png',
    description: 'An ethics case discussing a fast paced tech startup enviornment. Made to evoke critical ethical thinking.',
    link: 'https://docs.google.com/document/d/e/2PACX-1vRKgxLu2R6tAU-YF4OWMh2nmz7S07kL44N3sFvzWz334s9kzA0J1SFPHKMFbqc7bMcx78Pzq4kYHTmG/pub',
    tags: ['Non-Technical'],
  },
];
